# Generated by Django 3.2 on 2023-06-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerProfileModel',
            new_name='CustomerProfile',
        ),
        migrations.RenameModel(
            old_name='HospitalProfileModel',
            new_name='HospitalProfile',
        ),
    ]
