# Generated by Django 3.2 on 2023-06-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_user', '0002_auto_20230606_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
